<?php

return [
    'name' => 'PT. Syirkah Mandiri Artomoro',
    'tagline' => 'Industrial Supply & Integrated Technical Solutions',
    'description' => 'Partner industrial equipment, spare parts, dan solusi engineering di Pekanbaru untuk kebutuhan industri di Indonesia.',
    'profile' => 'PT. Syirkah Mandiri Artomoro menghubungkan produk global OEM dan principal dengan kebutuhan industri di Indonesia. Kami menyediakan equipment, spare parts, serta solusi engineering yang disesuaikan dengan kebutuhan dan spesifikasi pelanggan.',
    'address' => 'Jalan Teladan No. 7, RT 04/RW 10, Kel. Simpang Baru, Kec. Bina Widya, Kota Pekanbaru, Provinsi Riau 28293',
    'phone' => '+62 812-6672-3815',
    'phone_uri' => '+6281266723815',
    'emails' => ['doni.rahmat@smartomoro.com', 'admin@smartomoro.com'],
    'focus' => [
        ['name' => 'Engineering', 'icon' => 'drafting-compass', 'description' => 'Dukungan pemilihan equipment dan solusi teknis sesuai kebutuhan pengadaan Anda.'],
        ['name' => 'Mechanical', 'icon' => 'cog', 'description' => 'Equipment dan spare parts untuk mendukung sistem mekanikal industri.'],
        ['name' => 'Electrical', 'icon' => 'zap', 'description' => 'Motor, generator, dan drive control untuk kebutuhan penggerak industri.'],
        ['name' => 'Instrumentation', 'icon' => 'gauge', 'description' => 'Dukungan kebutuhan instrumentasi untuk pemantauan dan pengendalian proses.'],
        ['name' => 'Oil Spill Response & Prevention', 'icon' => 'shield-check', 'description' => 'Equipment untuk kesiapan penanganan dan pencegahan tumpahan minyak.'],
    ],
    'values' => [
        ['name' => 'Reliability', 'description' => 'Kesesuaian equipment dengan kebutuhan operasional menjadi prioritas.'],
        ['name' => 'Efficiency', 'description' => 'Pemilihan solusi yang mempertimbangkan efisiensi proses dan pengadaan.'],
        ['name' => 'Operational Continuity', 'description' => 'Dukungan equipment dan spare parts untuk keberlangsungan operasi.'],
        ['name' => 'Safety', 'description' => 'Pertimbangan keselamatan dalam pemilihan solusi teknis.'],
        ['name' => 'Environmental Protection', 'description' => 'Kesiapan penanganan tumpahan untuk mendukung perlindungan lingkungan.'],
    ],
    // Populate only with owner-approved public information.
    'legal' => [
        ['name' => 'NPWP', 'value' => null, 'public' => false],
        ['name' => 'SK Kemenkumham', 'value' => null, 'public' => false],
        ['name' => 'NIB', 'value' => null, 'public' => false],
    ],
    'products' => [
        'electric-motors-generators' => [
            'name' => 'Electric Motors & Generators', 'brand' => 'Wolong', 'brand_slug' => 'wolong', 'icon' => 'zap', 'group' => 'Electrical',
            'summary' => 'Sistem penggerak untuk kebutuhan elektrikal dan proses industri.',
            'description' => 'Pilihan motor listrik, generator, PM motor, dan drive control untuk mendukung sistem penggerak. Pemilihan tipe disesuaikan dengan kebutuhan daya, kondisi operasi, dan spesifikasi aplikasi Anda.',
            'types' => ['Electric motors', 'Generators', 'PM motors', 'Drive control'],
            'applications' => ['Sistem penggerak industri', 'Kebutuhan elektrikal dan pembangkitan'],
            'requirements' => ['Daya dan tegangan', 'Kecepatan putaran', 'Duty dan kondisi lingkungan'],
            'specifications' => [], 'image' => null, 'datasheet' => null,
        ],
        'vibration-technology' => [
            'name' => 'Vibration Technology', 'brand' => 'OLI', 'brand_slug' => 'oli', 'icon' => 'activity', 'group' => 'Mechanical',
            'summary' => 'Teknologi vibrasi untuk mendukung kebutuhan proses dan material.',
            'description' => 'Internal dan external vibrator, screen vibrator, serta converter untuk kebutuhan vibrasi. Diskusikan karakter material dan proses Anda untuk pemilihan equipment yang sesuai.',
            'types' => ['Internal vibrator', 'External vibrator', 'Screen vibrator', 'Converter'],
            'applications' => ['Proses penanganan material', 'Kebutuhan vibrasi industri dan konstruksi'],
            'requirements' => ['Jenis material', 'Kebutuhan vibrasi', 'Konfigurasi pemasangan'],
            'specifications' => [], 'image' => null, 'datasheet' => null,
        ],
        'chemical-metering-pump' => [
            'name' => 'Chemical Metering Pump', 'brand' => 'Qdos', 'brand_slug' => 'qdos', 'icon' => 'flask-conical', 'group' => 'Fluid Handling',
            'summary' => 'Chemical dosing pump untuk kebutuhan penakaran bahan kimia.',
            'description' => 'Solusi chemical metering untuk kebutuhan dosing pada proses industri. Jenis fluida, kebutuhan aliran, dan kondisi proses menjadi dasar pemilihan pompa.',
            'types' => ['Chemical dosing pump'],
            'applications' => ['Dosing bahan kimia', 'Proses pengolahan fluida'],
            'requirements' => ['Jenis dan konsentrasi bahan kimia', 'Flow rate dan tekanan', 'Kebutuhan kontrol dosing'],
            'specifications' => [], 'image' => null, 'datasheet' => null,
        ],
        'hose-pump' => [
            'name' => 'Hose Pump', 'brand' => 'Bredel', 'brand_slug' => 'bredel', 'icon' => 'droplets', 'group' => 'Fluid Handling',
            'summary' => 'Pompa hose untuk kebutuhan transfer fluida pada proses industri.',
            'description' => 'Pilihan hose pump untuk kebutuhan pemindahan fluida. Kesesuaian material hose dan karakteristik fluida perlu diperhatikan dalam menentukan konfigurasi pompa.',
            'types' => ['Hose pump'],
            'applications' => ['Transfer fluida industri', 'Sistem pemompaan proses'],
            'requirements' => ['Karakteristik fluida', 'Flow rate dan tekanan kerja', 'Kompatibilitas material hose'],
            'specifications' => [], 'image' => null, 'datasheet' => null,
        ],
        'industrial-hose' => [
            'name' => 'Industrial Hose', 'brand' => 'Aflex', 'brand_slug' => 'aflex', 'icon' => 'cable', 'group' => 'Fluid Handling',
            'summary' => 'PTFE hose untuk koneksi dan penyaluran fluida industri.',
            'description' => 'Pilihan PTFE hose untuk menghubungkan bagian sistem penyaluran fluida. Material, ukuran, dan koneksi dipilih berdasarkan kebutuhan aplikasi.',
            'types' => ['PTFE hose'],
            'applications' => ['Koneksi sistem fluida', 'Penyaluran fluida proses'],
            'requirements' => ['Diameter dan panjang hose', 'Jenis fluida dan temperatur', 'Tekanan kerja dan koneksi'],
            'specifications' => [], 'image' => null, 'datasheet' => null,
        ],
        'air-compressor' => [
            'name' => 'Air Compressor', 'brand' => 'Tecbell', 'brand_slug' => 'tecbell', 'icon' => 'wind', 'group' => 'Mechanical',
            'summary' => 'Air compressor dan refrigerated dryer untuk kebutuhan udara tekan.',
            'description' => 'Equipment udara tekan dan pengering udara untuk mendukung utilitas industri. Kebutuhan kapasitas, tekanan, dan kualitas udara menjadi dasar penentuan sistem.',
            'types' => ['Air compressor', 'Refrigerated dryer'],
            'applications' => ['Utilitas udara tekan', 'Kebutuhan udara pada proses industri'],
            'requirements' => ['Kapasitas udara', 'Tekanan kerja', 'Kebutuhan pengeringan udara'],
            'specifications' => [], 'image' => null, 'datasheet' => null,
        ],
        'oil-spill-response' => [
            'name' => 'Oil Spill Response & Prevention', 'brand' => 'BLU-C', 'brand_slug' => 'blu-c', 'icon' => 'shield-check', 'group' => 'Environmental',
            'summary' => 'Equipment untuk kesiapan respons dan penanganan tumpahan minyak.',
            'description' => 'Pilihan oil boom, absorbent, skimmer, dispersant, dan spill kit untuk kebutuhan penanganan tumpahan. Pemilihan equipment mempertimbangkan kondisi lokasi dan skenario respons.',
            'types' => ['Oil boom', 'Absorbent', 'Skimmer', 'Dispersant', 'Spill kit'],
            'applications' => ['Kesiapan respons tumpahan minyak', 'Penanganan tumpahan di area operasional'],
            'requirements' => ['Jenis dan potensi volume tumpahan', 'Kondisi area penanganan', 'Kebutuhan respons di lokasi'],
            'specifications' => [], 'image' => null, 'datasheet' => null,
        ],
    ],
    'solutions' => [
        ['name' => 'Sistem Penggerak', 'icon' => 'zap', 'description' => 'Dukung kebutuhan penggerak dan proses mekanikal dengan equipment yang sesuai dengan beban dan kondisi operasi.', 'products' => ['electric-motors-generators', 'vibration-technology']],
        ['name' => 'Fluid Handling', 'icon' => 'droplets', 'description' => 'Padukan kebutuhan dosing, transfer, dan koneksi fluida melalui pemilihan pompa serta hose yang sesuai.', 'products' => ['chemical-metering-pump', 'hose-pump', 'industrial-hose']],
        ['name' => 'Utilitas Industri', 'icon' => 'wind', 'description' => 'Penuhi kebutuhan udara tekan dan pengeringan udara untuk menunjang kelancaran operasi.', 'products' => ['air-compressor']],
        ['name' => 'Perlindungan Lingkungan', 'icon' => 'shield-check', 'description' => 'Siapkan equipment respons tumpahan berdasarkan kebutuhan dan kondisi area operasional Anda.', 'products' => ['oil-spill-response']],
    ],
];
