@extends('admin.layout')
@section('title', 'Produk')
@section('actions')<a class="a-button" href="{{ route('admin.products.create') }}"><x-icon name="plus" />Tambah Produk</a>@endsection
@section('content')
<form class="admin-filters" method="get"><x-admin.field name="q" label="Cari produk" :value="request('q')" type="search" /><x-admin.field name="state" label="Publikasi" :value="request('state')" type="select" :options="['' => 'Semua status', 'published' => 'Publik', 'draft' => 'Draft']" /><button class="a-button secondary"><x-icon name="search" />Cari</button><a href="{{ route('admin.products.index') }}">Reset</a></form>
<div class="table-wrap"><table class="admin-table"><thead><tr><th>Produk</th><th>Brand / Kategori</th><th>Status</th><th>Diperbarui</th><th><span class="sr-only">Tindakan</span></th></tr></thead><tbody>
@forelse($products as $product)<tr><td><div class="product-cell">@if($product->image)<img src="{{ asset($product->image) }}" alt="" width="44" height="44">@else<span class="thumb"><x-icon name="package" /></span>@endif<div><a href="{{ route('admin.products.edit', $product) }}">{{ $product->name }}</a><small>{{ $product->slug }}</small></div></div></td><td>{{ $product->brand->name }}<small>{{ $product->category->name }}</small></td><td><span class="status {{ $product->published ? 'published' : 'draft' }}">{{ $product->published ? 'Publik' : 'Draft' }}</span></td><td>{{ $product->updated_at->format('d M Y') }}</td><td><div class="row-actions"><a class="a-icon" href="{{ route('admin.products.edit', $product) }}" title="Edit {{ $product->name }}" aria-label="Edit {{ $product->name }}"><x-icon name="pencil" /></a>@if($product->published)<a class="a-icon" href="{{ route('products.show', $product->slug) }}" target="_blank" rel="noopener" title="Lihat produk" aria-label="Lihat {{ $product->name }}"><x-icon name="external-link" /></a>@endif<form method="post" action="{{ route('admin.products.destroy', $product) }}" data-confirm="Hapus produk ini? Tindakan ini tidak dapat dibatalkan.">@csrf @method('DELETE')<button class="a-icon danger" title="Hapus {{ $product->name }}" aria-label="Hapus {{ $product->name }}"><x-icon name="trash-2" /></button></form></div></td></tr>
@empty<tr><td colspan="5" class="empty-row">Tidak ada produk yang ditemukan.</td></tr>@endforelse
</tbody></table></div>@include('admin.partials.pagination', ['items' => $products])
@endsection
