@extends('layouts.app')
@section('title', $product['name'].' - '.$product['brand'])
@section('description', $product['summary'])
@section('content')
<section class="section product-detail"><div class="container">
    <nav class="breadcrumbs" aria-label="Breadcrumb"><a href="{{ route('products.index') }}">Produk</a><x-icon name="chevron-right" /><span>{{ $product['name'] }}</span></nav>
    <div class="detail-grid"><div class="product-visual">
        @if($product['image'])<img src="{{ asset($product['image']) }}" alt="{{ $product['name'] }} {{ $product['brand'] }}" width="800" height="640">@else<span class="visual-brand">{{ $product['brand'] }}</span><x-icon :name="$product['icon']" /><span class="visual-category">{{ $product['group'] }}</span><p>Foto produk tersedia melalui tim kami.</p>@endif
    </div><div class="detail-content"><p class="eyebrow">{{ $product['group'] }}</p><h1>{{ $product['name'] }}</h1><a class="brand-link" href="{{ route('brands.show', $product['brand_slug']) }}">{{ $product['brand'] }} <x-icon name="arrow-up-right" /></a><p class="lead">{{ $product['description'] }}</p><div class="actions"><a class="button" href="{{ route('contact', ['product' => $slug]) }}">Minta Penawaran <x-icon name="arrow-up-right" /></a>@if($product['datasheet'])<a class="button button-outline" href="{{ asset($product['datasheet']) }}" download><x-icon name="download" />Datasheet</a>@endif</div><p class="detail-note">Ketersediaan, tipe, dan spesifikasi dikonfirmasi sesuai kebutuhan Anda.</p></div></div>
    <div class="product-info-grid"><section><p class="eyebrow">Pilihan Produk</p><h2>Ruang lingkup pasokan</h2><ul class="check-list">@foreach($product['types'] as $type)<li><x-icon name="check" />{{ $type }}</li>@endforeach</ul><h3>Aplikasi</h3><ul class="plain-list">@foreach($product['applications'] as $application)<li>{{ $application }}</li>@endforeach</ul></section><section><p class="eyebrow">Informasi Teknis</p><h2>Spesifikasi & pemilihan</h2>@if(count($product['specifications']))<div class="table-scroll"><table><caption class="sr-only">Spesifikasi {{ $product['name'] }}</caption><tbody>@foreach($product['specifications'] as $label => $value)<tr><th scope="row">{{ $label }}</th><td>{{ $value }}</td></tr>@endforeach</tbody></table></div>@else<p>Spesifikasi teknis bergantung pada model dan konfigurasi. Hubungi tim kami untuk informasi model dan datasheet yang sesuai.</p>@endif<h3>Parameter kebutuhan</h3><ul class="plain-list">@foreach($product['requirements'] as $requirement)<li>{{ $requirement }}</li>@endforeach</ul></section></div>
</div></section>
<section class="section section-soft"><div class="container"><div class="section-heading"><h2>Kategori lainnya</h2><a class="text-link" href="{{ route('products.index') }}">Semua Produk <x-icon name="arrow-up-right" /></a></div><div class="product-grid">@foreach($related as $relatedSlug => $item)<x-product-card :product="$item" :slug="$relatedSlug" />@endforeach</div></div></section>
@endsection
